version: '3.4'

services:
    mongo:
        image: mongo:latest
        environment:
          MONGO_USER: mongo
          MONGO_PASSWORD: mongo   
        ports:
          - 5436:5432

    rust:
        image: gachu/front-eam:latest
        ports: 
            - 8080:8080
    moleculer:
        image: gachu/back-eam:latest
        ports: 
                - 3000:3000
        depends_on:
                - mongo
